### ISSUE TITLE
Remember if User Chose Detailed or Simple View

### ISSUE THREAD

**Issue by OwenMcGee** [quatalog/quatalog#3]
Currently if a user is looking at a course's information, and clicks a link to another course (such as one listed in the pre-req section), the site will always default to Simple View. Ideally, I would think that if the user had chosen Detailed View, the site should stay in Detailed View until the user chooses to revert back to Simple View.

**Comment by Phantop** [comment]
Dunno the state of active Quatalog development at this point, but will note that if you use any browser extensions that support userstyles/custom  CSS you can use the following to force detailed view:

```css
#years-table .detail-view-container {
  display: flex;
}
#years-table td {
  background-image: unset;
}
```
